### ISSUE TITLE
X-XSS-Protection upgrade option possible ?

### ISSUE THREAD

**Issue by yugandharkommineni** [apple/swift-http-types#39]
Steps To Reproduce:
Perform any action and capture the HTTP Request.(iOS mobile apps with swift code)
Observe that in response X-XSS-Protection header was used.
HTTP/2
200 
OK
Server :jag
Etag: 3655723661770096640-4617501349922598127
Content-Type:text/html;charset=utf-8
Content-Length:1
**X-Xss-Protection: 1; mode=block**

Recommendation:
Disable use of deprecated headers such as X-XSS-Protection.

References
[X-XSS-Protection - HTTP | MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) 

Impact
Even though this feature can protect users of older web browsers that don't yet support Content-Security-Policy, in some cases, XSS protection can create XSS vulnerabilities in otherwise safe websites.

**Comment by guoye-zhang** [comment]
This package provides low-level representations of HTTP request and response fields. Policing a specific header field is out of scope. Please direct bug reports to the specific service that's generating these headers.
