### ISSUE TITLE
`URLSession` convenience methods not available on non-Apple platforms

### ISSUE THREAD

**Issue by fumoboy007** [apple/swift-http-types#40]
The `URLSession` convenience methods are currently [only available on Apple platforms](https://github.com/apple/swift-http-types/blob/1827dc94bdab2eb5f2fc804e9b0cb43574282566/Sources/HTTPTypesFoundation/URLSession%2BHTTPTypes.swift#L43). Why is that?

**Comment by guoye-zhang** [comment]
These convenience methods are based on async URLSession conveniences, but swift-corelibs-foundation does not current have those implemented.

**Comment by fumoboy007** [comment]
Ah, https://github.com/apple/swift-corelibs-foundation/issues/3205. 🥲
