### ISSUE TITLE
Build issue on nightly-6.0-amazonlinux2

### ISSUE THREAD

**Issue by AndrewBarba** [apple/swift-http-types#61]
I'm currently experiencing build issues on `nightly-6.0-amazonlinux2`. Appears related to the new `Foundation` on nightly:

```
/workspace/.build/checkouts/swift-http-types/Sources/HTTPTypesFoundation/HTTPRequest+URL.swift:15:8: error: no such module 'CoreFoundation'
 13 | //===----------------------------------------------------------------------===//
 14 | 
 15 | import CoreFoundation
    |        `- error: no such module 'CoreFoundation'
 16 | import Foundation
 17 | import HTTPTypes
```

Edit: Full command used to build

```
/usr/local/bin/docker run \
  --platform linux/arm64 \
  --rm \
  -v ./:/workspace \
  -w /workspace \
  swiftlang/swift:nightly-6.0-amazonlinux2 bash -cl swift build -c release -Xswiftc -Osize --static-swift-stdlib
```

**Comment by guoye-zhang** [comment]
@jrflat Do you know what’s happening there?

**Comment by Lukasa** [comment]
I believe CoreFoundation is not intended to be part of the x-platform piece of Foundation, and so we probably shouldn't depend on it. This is probably related to re-homing Foundation on swift-foundation.

**Comment by FranzBusch** [comment]
I agree. We **must never** import `CoreFoundation` on non-Darwin platforms. We don't guarantee any stability around that and with the re-core `CoreFoundation` is going away long term on non-Darwin platforms

**Comment by guoye-zhang** [comment]
This CoreFoundation dependency is unfortunately unavoidable today unless Foundation URL starts supporting WHATWG parsing.

**Comment by jmschonfeld** [comment]
Yes `CoreFoundation` is not public API on non-Darwin and should not be relied upon outside of swift-corelibs-foundation so it should be removed from here. That being said, I don't think we explicitly removed the `CoreFoundation` module in the re-core and we still have projects that import it (incorrectly) that are successfully building. I can also successfully import the module from `swift repl` inside of a `nightly-amazonlinux2` container. Let me check `nightly-6.0-amazonlinux2`

**Comment by jmschonfeld** [comment]
While I do not advocate for any CF code, the following does still appear to be functional to me on the latest nightly-6.0-amazonlinux2 container:

```
root@nightly-6 Repos]# swift test.swift
16
[root@nightly-6 Repos]# cat test.swift
import CoreFoundation
import Foundation

var url = URL(string: "http://apple.com")! as NSURL
let cf = unsafeBitCast(url, to: CFURL.self)
let length = CFURLGetBytes(cf, nil, 0)
print(length)[root@nightly-6 Repos]# swift test.swift
16
[root@nightly-6 Repos]# cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```

**Comment by AndrewBarba** [comment]
@jmschonfeld Here is full command I'm running to build:

```
/usr/local/bin/docker run \
  --platform linux/arm64 \
  --rm \
  -v ./:/workspace \
  -w /workspace \
  swiftlang/swift:nightly-6.0-amazonlinux2 bash -cl swift build -c release -Xswiftc -Osize --static-swift-stdlib
```

**Comment by jmschonfeld** [comment]
Aha, that `--static-swift-stdlib` is the key:

```
[root@nightly-amazonlinux2 Repos]# swiftc -static-stdlib test.swift                                                                                                                                                                                                                                                                                                        
/Repos/test.swift:1:8: error: no such module 'CoreFoundation'
1 | import CoreFoundation
  |        `- error: no such module 'CoreFoundation'
2 | import Foundation
3 | 
[root@nightly-amazonlinux2 Repos]# swiftc test.swift
<no output>
```

Looks like the CoreFoundation module was removed from the static swift build
