### ISSUE TITLE
More consistent naming for HTTPFields subscripts

### ISSUE THREAD

**Issue by guoye-zhang** [apple/swift-http-types#9]
HTTPFields currently have 3 subscripts: `subscript(_: HTTPField.Name) -> String?`, `subscript(raw: HTTPField.Name) -> [String]`, and `subscript(fields: HTTPField.Name) -> [HTTPField] `.

- The first one `subscript(_: HTTPField.Name) -> String?` is equivalent to Foundation URLRequest/HTTPURLResponse `value(forHTTPHeaderField:)`.
- The second one `subscript(raw: HTTPField.Name) -> [String]` is equivalent to NIO `HTTPHeaders.subscript(_:)`.
- The third one has no equivalence in previous APIs since HTTPField is a new abstraction.
- There is no equivalence to NIO `HTTPHeaders.subscript(canonicalForm:)`.

During past discussions, it's been brought up that `raw` is a weird name, and "fields" is more "raw" than `raw`. Let's figure out if there is a better set of names for these subscripts.

**Comment by guoye-zhang** [comment]
Alternatives for `raw`:

- all
- array
- multiValue
- values
- split
- parts

**Comment by guoye-zhang** [comment]
Alternatively, we could rename `fields` to `rawFields`

**Comment by jbehrens94** [comment]
I would suggest `allHttpFields` / `allHTTPFields`. That feels closest to the current Foundation implementation.

**Comment by guoye-zhang** [comment]
> I would suggest `allHttpFields` / `allHTTPFields`. That feels closest to the current Foundation implementation.

 `all` kind of describes every variant of the subscript, not capturing the difference of combined value vs split values.
